name: test_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  flutter_lints: ^2.0.1
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  flutter_native_splash: ^2.2.19
  firebase_auth: ^4.2.10
  google_sign_in: ^6.0.2
  flutter_overboard: ^3.1.1
  shared_preferences: ^2.0.20

flutter:
  uses-material-design: true

  assets:
  - assets/icon.png
  - assets/icon_big.png
  - assets/background.png

flutter_native_splash:
  color: "ffe26b"
  image: assets/icon.png
