// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU2la0toHmBl_X2xYs6Pu5yFZr4NoVgw4',
    appId: '1:356300846998:web:13c40361517d57728fcfb7',
    messagingSenderId: '356300846998',
    projectId: 'diaryapp-f7fb1',
    authDomain: 'diaryapp-f7fb1.firebaseapp.com',
    storageBucket: 'diaryapp-f7fb1.appspot.com',
    measurementId: 'G-Z8N2FW8CN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgBRl8steLip8XvYVtuUsCP7LAm4_l4Qc',
    appId: '1:356300846998:android:43765ee4fceb16018fcfb7',
    messagingSenderId: '356300846998',
    projectId: 'diaryapp-f7fb1',
    storageBucket: 'diaryapp-f7fb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwVXUoCU7eoyGp_kpntOWP_d68ICn6UdU',
    appId: '1:356300846998:ios:f0a9f404d4ce94058fcfb7',
    messagingSenderId: '356300846998',
    projectId: 'diaryapp-f7fb1',
    storageBucket: 'diaryapp-f7fb1.appspot.com',
    iosClientId: '356300846998-nl156brd2b068055nut4i3u5rn451ju6.apps.googleusercontent.com',
    iosBundleId: 'com.example.onedaydiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwVXUoCU7eoyGp_kpntOWP_d68ICn6UdU',
    appId: '1:356300846998:ios:f0a9f404d4ce94058fcfb7',
    messagingSenderId: '356300846998',
    projectId: 'diaryapp-f7fb1',
    storageBucket: 'diaryapp-f7fb1.appspot.com',
    iosClientId: '356300846998-nl156brd2b068055nut4i3u5rn451ju6.apps.googleusercontent.com',
    iosBundleId: 'com.example.onedaydiary',
  );
}
